name: CI
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repository: eritpchy/homebrew-core
    # - name: Set up Flutter
    #   uses: subosito/flutter-action@v2
    #   with:
    #     channel: stable
    #     flutter-version: 3.19.0
    # - name: Tmate set mouse on
    #   run: echo "set -g mouse on"  >> ~/.tmux.conf
    # - name: Flutter build
    #   run: flutter build macos -v
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"
        activate-environment: "videoEnv"
    - name: Prepare python env
      shell: bash -el {0}
      run: |
        which python 
        which pip 
        conda activate videoEnv
        which python 
        conda info
        conda list
        for package in ${{ secrets.VSP_REQUMENTS }}; do
          echo "::add-mask::${package}"
          pip install ${package}
        done
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3