name: CI
on:
  workflow_dispatch:
    inputs:
        macOSVersion:
          description: 'macOS Version'
          required: true
          default: 'macos-14'
          type: choice
          options:
          - macos-14
          - macos-13
          - macos-12
  push:

jobs:
  build:
    runs-on: ${{ inputs.macOSVersion || 'macos-14'}}
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repository: eritpchy/homebrew-core
        path: "homebrew-core"
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0
    # - name: Tmate set mouse on
    #   run: echo "set -g mouse on"  >> ~/.tmux.conf
    # - name: Flutter build
    #   run: flutter build macos -v

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    # - uses: conda-incubator/setup-miniconda@v3
    #   with:
    #     auto-update-conda: true
    #     python-version: "3.10"
    #     activate-environment: "videoEnv"
    # - name: Prepare python env
    #   shell: bash -el {0}
    #   run: |
    #     which python 
    #     which pip 
    #     conda activate videoEnv
    #     which python 
    #     conda info
    #     conda list
    #     for package in ${{ secrets.VSP_REQUMENTS }}; do
    #       echo "::add-mask::${package}"
    #       pip install ${package}
    #     done
    - uses: fawazahmed0/action-debug@main
      with:
          credentials: "${{ secrets.ACTION_USER }}:${{ secrets.ACTION_PASS }}"
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3