name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0
    - name: Tmate set mouse on
      run: echo "set -g mouse on"  >> ~/.tmux.conf
    - name: Flutter build
      run: flutter build macos -v
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        activate-environment: ""
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3